services:
  desktop:
    container_name: desktop4ds
    image: obuntu
    build:
      context: ./container
      dockerfile: Dockerfile
      args:
        - USER_NAME=ds
    environment:
      - USER_GROUP=ds 
      - USER_GID=1010
      - USER_NAME=ds
      - USER_UID=1010
      - USER_PASSWORD=vncpassword
      - VNC_RESOLUTION=1920x1200
      - GRANT_SUDO=yes
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDA_VISIBLE_DEVICES=0
      - ENABLE_USER_DAEMON=0
    init: true
    restart: unless-stopped
    shm_size: '4294967296'
    ipc: host
    ulimits:
      memlock: -1 
    hostname: DataScience
    mac_address: "02:42:da:ce:2f:f3"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    user: root
    ports:
      - "40022:8022"
      - "40059:5901"
      - "40069:6901"
      - "40038:3838"
      - "40087:8787"
      - "40088:8888"
      - "40080:8000"
    command: |
      bash -c "exec /usr/bin/supervisord -c ~/.local/etc/supervisor/supervisord.conf --nodaemon"
    volumes:
      - /tmp/docker-tmp-ds:/tmp
      - /tmp/nvidia-mps:/tmp/nvidia-mps
      - /home/ds:/home/ds:rshared
      - /opt/:/srv/:rshared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
